apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.psp_ui.psp_ui_namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
  
{{- define "imagePullSecret" }}
{{- with .Values.psp_ui }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .psp_ui_registry .psp_ui_registry_username .psp_ui_registry_password .psp_ui_registry_email (printf "%s:%s" .psp_ui_registry_username .psp_ui_registry_password | b64enc) | b64enc }}
{{- end }}
{{- end }}
