apiVersion: v1
kind: Service
metadata:
  name: psp-ui
  namespace: {{ .Values.psp_ui.psp_ui_namespace }}
  labels:
    app: psp-ui
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
  - port: 4001
  selector:
    app: psp-ui
