apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.igs.igs_namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
  DATABASE_USERNAME: {{ .Values.igs.igs_database_user }}
  DATABASE_PASSWORD: {{ .Values.igs.igs_database_password }} 
  
{{- define "imagePullSecret" }}
{{- with .Values.igs }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .igs_registry .igs_registry_username .igs_registry_password .igs_registry_email (printf "%s:%s" .igs_registry_username .igs_registry_password | b64enc) | b64enc }}
{{- end }}
{{- end }}
