apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: {{ .Values.mongodb.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mongodb
  volumeName: mongodb-pv
  resources:
    requests:
      storage: 2Gi
