apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: {{ .Values.mongodb.namespace }}
type: Opaque
data:
  MONGO_ROOT_USERNAME: {{ .Values.mongodb.root_user }} 
  MONGO_ROOT_PASSWORD: {{ .Values.mongodb.root_password }}
  MONGO_USERNAME: {{ .Values.mongodb.igs_user }}
  MONGO_PASSWORD: {{ .Values.mongodb.igs_password }} 
  MONGO_USERS_LIST: {{ .Values.mongodb.user_roles }}
  MONGO_DATABASE_NAME: {{ .Values.mongodb.database_name }}
